# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure til studerende (a52df485-da39-47f1-beac-ac42b035fcba)'
    appType: 'webAppLinux'
    WebAppName: 'dotnettest'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    StartupCommand: 'dotnet run ./Server'
