trigger:
- master

pool:
  vmimage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      version: '5.0.x'
      includePreviewVersions: true # Required for preview versions
    displayName: 'Using Dotnet 5.0'  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '*/.csproj'
    displayName: 'Building...'  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
    displayName: 'Publishing...'  